apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: vifi/k8s-demo:v1
          name: demo
          ports:
            - name: readiness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: readiness-port
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 5"]
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: default
spec:
  ports:
    - port: 8080
  type: LoadBalancer
  selector:
    app: demo
